### ISSUE TITLE
Dream Stats

### ISSUE THREAD

**Issue by brannondorsey** [brangerbriz/webroutes#15]
Addon screen could display things like:
- [x] ISPs Traversed
- [x] Borders crossed
- [x] [Autonomous Systems](https://en.wikipedia.org/wiki/Autonomous_system_%28Internet%29) Traversed

**Comment by nbriz** [comment]
number of hops: 20,

country borders crossed: 5,

networks traversed: 3,

networks exchanged data at the following exchange points:
    - name [location]
    - name [location]

networks run by the following ISPs:
    - Comcast
    - Google

submarine cables crossed:
    - name [ owenr ]

**Comment by brannondorsey** [comment]
Done.
