### ISSUE TITLE
gallery ready

### ISSUE THREAD

**Issue by nbriz** [brangerbriz/webroutes#24]
- [x] come up w/a solid kiosk mode plan for IRL installation ( so folks don't exit out )
- [ ] come up w/start up scripts && watch scripts
- [ ] figure a way to kill Meta/Alt keys
- [x] detect screen ( 1 or 2 ) && place windows appropriately on launch
- [x] hide mouse && prevent mouse defaults
- [x] ensure that address bar is always in focus

**Comment by brannondorsey** [comment]
Use NW kiosk mode + CompizConfig Settings Manager to disable super key behavior.

**Comment by nbriz** [comment]
think we don't need compiz, could just disable the keyboard shortcuts in settings

**Comment by brannondorsey** [comment]
Got a live USB w/ persistence working after like 4 hours of trying different things.

**Comment by nbriz** [comment]
awsum!!! :D we should stress test tomorrow && ship it ASAP ^___^

**Comment by brannondorsey** [comment]
Sounds good!
